<?php
require_once 'PHPUnit/Framework.php';
require_once 'PHPUnit/Extensions/OutputTestCase.php';
require_once dirname(__FILE__) . '/../BuggyPress.class.php';
require_once '/usr/lib/mockpress/mockpress.php';

/**
 * Test class for BuggyPress.
 * Generated by PHPUnit on 2011-05-15 at 17:33:49.
 */
class BuggyPressTest extends PHPUnit_Extensions_OutputTestCase {

	public static function setUpBeforeClass() {
		define('WP_PLUGIN_DIR', '/wordpress/dir/wp-content/plugins');
		define('WP_PLUGIN_URL', 'http://example.org/wp-content/plugins');
	}

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp( ) {
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown( ) {
	}

	public function string_provider() {
		return array(
			array('test'),
			array(3),
			array(3.0),
			array(NULL),
		);
	}

	/**
	 * @dataProvider string_provider
	 */
	public function test__( $a ) {
		$this->assertEquals($a, BuggyPress::__($a));
	}

	/**
	 * @dataProvider string_provider
	 */
	public function test_e( $a ) {
		$this->expectOutputString($a);
		BuggyPress::_e($a);
	}

	/**
	 *
	 */
	public function testPlugin_path( ) {
		$this->assertEquals('/wordpress/dir/wp-content/plugins/BuggyPress', BuggyPress::plugin_path());
	}

	/**
	 *
	 */
	public function testPlugin_url( ) {
		$this->assertEquals('http://example.org/wp-content/plugins/BuggyPress', BuggyPress::plugin_url());
	}
}

?>
