<?php
require_once 'PHPUnit/Framework.php';
require_once 'PHPUnit/Extensions/OutputTestCase.php';
require_once dirname(__FILE__) . '/../BuggyPress.class.php';
require_once '/usr/lib/mockpress/mockpress.php';

/**
 * Test class for BuggyPress.
 * Generated by PHPUnit on 2011-05-15 at 17:33:49.
 */
class BuggyPressTest extends PHPUnit_Extensions_OutputTestCase {

	public static function setUpBeforeClass() {
		define('WP_PLUGIN_DIR', '/wordpress/dir/wp-content/plugins');
		define('WP_PLUGIN_URL', 'http://example.org/wp-content/plugins');
	}

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp( ) {
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown( ) {
		_reset_wp();
	}

	public function string_provider() {
		return array(
			array('test'),
			array(3),
			array(3.0),
			array(NULL),
		);
	}

	/**
	 * @dataProvider string_provider
	 */
	public function test__( $a ) {
		$this->assertEquals($a, BuggyPress::__($a));
	}

	/**
	 * @dataProvider string_provider
	 */
	public function test_e( $a ) {
		$this->expectOutputString($a);
		BuggyPress::_e($a);
	}

	/**
	 *
	 */
	public function testPlugin_path( ) {
		$this->assertEquals('/wordpress/dir/wp-content/plugins/BuggyPress', BuggyPress::plugin_path());
	}

	/**
	 *
	 */
	public function testPlugin_url( ) {
		$this->assertEquals('http://example.org/wp-content/plugins/BuggyPress', BuggyPress::plugin_url());
	}


	public function version_provider() {
		return array(
			array('4.3', '2.5', FALSE),
			array('5.2', '3.0', FALSE),
			array('5.2', '3.1', TRUE),
			array('5.2.18', '3.1.2', TRUE),
			array('5.3', '3.1.1', TRUE),
			array('5.1', '3.1', FALSE),
		);
	}

	/**
	 * @dataProvider version_provider
	 */
	public function testPrerequisites_met( $php, $wp, $result ) {
		$this->assertEquals($result, BuggyPress::prerequisites_met($php, $wp));
	}

	public function testFailed_to_load_notices() {
		$this->expectOutputString('<div class="error"><p>BuggyPress requires WordPress 3.1 or higher and PHP 5.2 or higher.</p></div>');
		BuggyPress::failed_to_load_notices('5.2', '3.1');
	}

	/**
	 * @dataProvider action_provider
	 */
	public function testAdd_action($name, $callback, $priority, $accepted_args) {
		BuggyPress::add_action($name, $callback, $priority, $accepted_args);
		global $wp_test_expectations;
		$this->assertArrayHasKey($name, $wp_test_expectations['actions']);

		// not an exact mirror of real WP, but works for our test suite
		$this->assertEquals($callback, $wp_test_expectations['actions'][$name]);
	}

	/**
	 * @dataProvider action_provider
	 */
	public function testAdd_filter($name, $callback, $priority, $accepted_args) {
		BuggyPress::add_filter($name, $callback, $priority, $accepted_args);
		global $wp_test_expectations;
		$this->assertArrayHasKey($name, $wp_test_expectations['filters']);
		$this->assertArrayHasKey($priority, $wp_test_expectations['filters'][$name]);
		$this->assertContains($callback, $wp_test_expectations['filters'][$name][$priority]);
	}

	public function action_provider() {
		return array(
			array('init', 'initialize', 10, 0),
			array('init', array('BuggyPress', 'initialize'), 10, 0),
			array('init', array($this, 'initialize'), 10, 0),
			array('wp', 'handle_callbacks', 0, 1),
		);
	}
}

?>
